### ISSUE TITLE
Using squr with odbc package?

### ISSUE THREAD

**Issue by ThoDuyNguyen** [smbache/squr#5]
Hi 

I come across to the link about `odbc` package 
https://www.rstudio.com/resources/videos/database-best-practices/

The performance of `odbc` looks promising. 
Is there any chance `squr` be updated using `odbc` instead of `rodbc`? 

Thank you in advance.

**Comment by smbache** [comment]
`squr` does not use `RODBC`, or any other specific connectivity. There is an `RODBC` example, but you can use whatever you want, including `odbc` :)

**Comment by ThoDuyNguyen** [comment]
Thank you for answering.
