### ISSUE TITLE
Example for transaction execute

### ISSUE THREAD

**Issue by ThoDuyNguyen** [smbache/squr#7]
Hi

My scenario is: 

- Truncate multiple data tables in database
- Insert data from multiple data frames to database. Let say, data frame name `a1`, `a2`

I want to wrap these action into an transaction. Thus, I prepare a script for all `truncate` command name `truncate.sql`. 

Does the code below achieve what I need: 

```
truncate <- sq_file('truncate.sql')


result <-
  sq_transaction(truncate) %>%
  sq_insert(.into = "a1", .data = a1) %>%
  sq_insert(.into = "a2", .data = a2) %>%
  sq_send(.with = rodbc)
```

Thank you in advance.

**Comment by ThoDuyNguyen** [comment]
I re-read carefully the document and the `Insertion Blocks` solved my problem.

**Comment by smbache** [comment]
Fantastic!
